# Netlify configuration file
[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Redirects and rewrites
[[redirects]]
  from = "/archive"
  to = "/archive/1"
  status = 301

# Headers are defined in _headers file

# Plugin configuration (optional)
[[plugins]]
  package = "@netlify/plugin-lighthouse"

  # Lighthouse configuration
  [plugins.inputs.thresholds]
    performance = 0.9
    accessibility = 0.9
    best-practices = 0.9
    seo = 0.9
