name = "dhwani"
main = "worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Static assets
assets = { directory = "./dist", binding = "ASSETS" }

# Custom domain
route = "dhwani.ink/*"
routes = [
  { pattern = "dhwani.ink/*", custom_domain = true }
]

# Build configuration
[build]
command = "npm run build"

# Environment variables (if needed)
# [vars]
# API_KEY = "your-api-key"

# Production optimizations
[env.production]
compatibility_date = "2024-09-23"

# Observability
observability = { enabled = true }
