name = "dhwani"
pages_build_output_dir = "dist"
compatibility_date = "2024-09-23"

# Build configuration
[build]
command = "npm run build"

# Environment variables (if needed)
# [vars]
# API_KEY = "your-api-key"

# Production optimizations
[env.production]
compatibility_date = "2024-09-23"

# Observability
observability = { enabled = true }
