name = "dhwani"
main = "worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Static assets
[assets]
directory = "./dist"

# Environment variables (if needed)
# [vars]
# API_KEY = "your-api-key"

# Production optimizations
[env.production]
compatibility_date = "2024-09-23"

# Observability
observability = { enabled = true }
